from ..state import State
from litellm import completion
import os

def aggregator_node(state: State):
    """
    Aggregates results from subtasks and synthesizes a final response.
    """
    subtasks = state["subtasks"]
    user_input = state["user_input"]
    print("--- Aggregating Results ---")
    
    results = [f"Subtask ({task.id}): {task.result}" for task in subtasks if task.result]
    
    if not results:
        return {"final_output": "No results were generated by subtasks."}
    
    results_text = "\n\n".join(results)
    
    model = os.getenv("MAIN_LLM_MODEL", "openrouter/google/gemini-2.0-flash-lite-preview-02-05:free")
    
    prompt = f"""
    You are a Result Aggregator. Your task is to take the outputs from several specialized subtasks and synthesize them into a single, coherent, and comprehensive response that directly addresses the original user request.
    
    Original User Request: {user_input}
    
    Subtask Results:
    {results_text}
    
    Instructions:
    1.  Synthesize the information into a logical flow.
    2.  Ensure all parts of the user's request are addressed.
    3.  Remove any redundant information or conflicting statements.
    4.  Maintain a professional and helpful tone.
    5.  The final output should be the complete answer to the user, not a summary of the tasks.
    
    Final Synthesized Response:
    """
    
    try:
        response = completion(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert synthesizer. Your goal is to provide a final, polished response based on multiple input sources."},
                {"role": "user", "content": prompt}
            ]
        )
        final_output = response.choices[0].message.content
        print(f"Aggregation complete. Length: {len(final_output)} characters.")
        
        return {"final_output": final_output}
    except Exception as e:
        print(f"Error during aggregation: {e}")
        # Fallback to simple concatenation if LLM fails
        return {"final_output": "\n\n".join([task.result for task in subtasks if task.result])}
