from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import json
import os

class ModelCapability(BaseModel):
    model_id: str
    capabilities: List[str]
    cost_per_1k_tokens: float = 0.0
    latency_score: int
    description: str

class CapabilityRegistry:
    def __init__(self):
        self.models: List[ModelCapability] = []
        self.load_models()

    def load_models(self):
        """
        Loads free models from the JSON file generated by the update script.
        """
        file_path = os.path.join(os.path.dirname(__file__), "free_models.json")
        if os.path.exists(file_path):
            try:
                with open(file_path, "r") as f:
                    data = json.load(f)
                    self.models = [ModelCapability(**m) for m in data]
                print(f"[REGISTRY] Loaded {len(self.models)} free models.")
            except Exception as e:
                print(f"[REGISTRY] Error loading free models: {e}")
        
        if not self.models:
            # Minimal fallback
            self.models = [
                ModelCapability(
                    model_id="openrouter/google/gemini-2.0-flash-lite-preview-02-05:free",
                    capabilities=["general", "reasoning", "research"],
                    latency_score=2,
                    description="Fallback free model"
                )
            ]

    def get_best_model(self, required_capabilities: List[str]) -> str:
        """
        Selects the best free model based on capabilities and latency.
        """
        scored_models = []
        
        for model in self.models:
            # Calculate match score based on how many required capabilities the model has
            match_count = sum(1 for cap in required_capabilities if cap in model.capabilities)
            
            if match_count > 0 or not required_capabilities:
                # Score = Latency + (Penalty for missing capabilities)
                # Lower score is better
                missing_count = len(required_capabilities) - match_count
                score = model.latency_score + (missing_count * 5)
                
                # Tie-breaker: prefer models with more relevant capabilities if scores are equal
                # or models with fewer TOTAL capabilities (specialized)
                # We'll use a tuple for sorting: (score, total_capabilities)
                scored_models.append((model.model_id, score, len(model.capabilities)))
        
        if not scored_models:
            return self.models[0].model_id
            
        # Sort by score (asc), then total_capabilities (asc) for specialization
        scored_models.sort(key=lambda x: (x[1], x[2]))
        return scored_models[0][0]

# Global registry instance
registry = CapabilityRegistry()
