from typing import List, Dict, Any, Optional
from pydantic import BaseModel
import json
import os

# The only capability values the registry and router understand. The analyzer is
# instructed to emit these; anything else is normalized or dropped.
CANONICAL_CAPABILITIES = [
    "general",
    "coding",
    "reasoning",
    "research",
    "summarization",
    "creative",
    "image",
]

# Common drift / synonyms the LLM produces, mapped to the canonical vocabulary.
_CAPABILITY_ALIASES = {
    "creativity": "creative",
    "creative_writing": "creative",
    "writing": "creative",
    "image_generation": "image",
    "image-generation": "image",
    "vision": "image",
    "multimodal": "image",
    "code": "coding",
    "programming": "coding",
    "summarize": "summarization",
    "summary": "summarization",
    "logic": "reasoning",
    "math": "reasoning",
}


def normalize_capabilities(capabilities: List[str]) -> List[str]:
    """
    Maps free-form capability strings onto the canonical vocabulary.
    Lowercases, applies known aliases, and drops anything unrecognized.
    Preserves order and removes duplicates. Never raises.
    """
    normalized: List[str] = []
    for raw in capabilities or []:
        if not isinstance(raw, str):
            continue
        cap = raw.strip().lower()
        cap = _CAPABILITY_ALIASES.get(cap, cap)
        if cap in CANONICAL_CAPABILITIES and cap not in normalized:
            normalized.append(cap)
    return normalized


class ModelCapability(BaseModel):
    model_id: str
    capabilities: List[str]
    cost_per_1k_tokens: float = 0.0
    latency_score: int # 1-10, lower is faster
    reasoning_score: int = 5 # 1-10, higher is better
    coding_score: int = 5 # 1-10, higher is better
    creativity_score: int = 5 # 1-10, higher is better
    description: str

class CapabilityRegistry:
    def __init__(self):
        self.models: List[ModelCapability] = []
        self.load_models()

    def load_models(self):
        """
        Loads free models from the JSON file generated by the update script.
        """
        file_path = os.path.join(os.path.dirname(__file__), "free_models.json")
        if os.path.exists(file_path):
            try:
                with open(file_path, "r") as f:
                    data = json.load(f)
                    self.models = [ModelCapability(**m) for m in data]
                print(f"[REGISTRY] Loaded {len(self.models)} free models.")
            except Exception as e:
                print(f"[REGISTRY] Error loading free models: {e}")
        
        if not self.models:
            # Minimal fallback
            self.models = [
                ModelCapability(
                    model_id="openrouter/google/gemini-2.0-flash-lite-preview-02-05:free",
                    capabilities=["general", "reasoning", "research"],
                    latency_score=2,
                    reasoning_score=8,
                    coding_score=7,
                    creativity_score=6,
                    description="Fallback free model"
                )
            ]

    def get_best_model(self, required_capabilities: List[str], exclude_models: List[str] = None) -> str:
        """
        Selects the best free model based on capabilities and performance scores.
        Allows excluding specific models (e.g., if they are rate-limited or dead).
        """
        exclude_models = exclude_models or []
        required_capabilities = normalize_capabilities(required_capabilities)
        scored_models = []

        for model in self.models:
            if model.model_id in exclude_models:
                continue

            # Calculate match score based on how many required capabilities the model has
            match_count = sum(1 for cap in required_capabilities if cap in model.capabilities)

            if match_count > 0 or not required_capabilities:
                # Base score from latency (lower is better)
                # Weighted penalty for missing capabilities
                missing_count = len(required_capabilities) - match_count
                score = model.latency_score + (missing_count * 10)
                
                # Quality Boost: Subtract quality scores from the "badness" score
                # This makes high-quality models more attractive even if slightly slower
                quality_bonus = 0
                if "reasoning" in required_capabilities:
                    quality_bonus += model.reasoning_score
                if "coding" in required_capabilities:
                    quality_bonus += model.coding_score
                if "creative" in required_capabilities:
                    quality_bonus += model.creativity_score
                
                # Scale quality bonus to have meaningful impact (0-10 -> 0-5)
                score -= (quality_bonus * 0.5)

                # Tie-breaker: prefer models with fewer TOTAL capabilities (specialized)
                scored_models.append((model.model_id, score, len(model.capabilities)))

        if scored_models:
            # Sort by score (asc), then total_capabilities (asc) for specialization
            scored_models.sort(key=lambda x: (x[1], x[2]))
            return scored_models[0][0]

        # No capability match: fall back to the best general-purpose model rather
        # than blindly returning the first JSON entry (which may be dead/incapable).
        return self._fallback_model(exclude_models)

    def _fallback_model(self, exclude_models: List[str]) -> str:
        """
        Picks a sensible model when capability matching yields nothing:
        best general-capable non-excluded model, else any non-excluded model,
        else the first model as a last resort.
        """
        general = [m for m in self.models if m.model_id not in exclude_models and "general" in m.capabilities]
        if general:
            return min(general, key=lambda m: m.latency_score).model_id

        available = [m for m in self.models if m.model_id not in exclude_models]
        if available:
            return min(available, key=lambda m: m.latency_score).model_id

        return self.models[0].model_id

# Global registry instance
registry = CapabilityRegistry()
